import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  outputFileTracingIncludes: {
    "/api/generate-render{,/test}": [
      "./scripts/**/*",
      "./generator/**/*",
      // sharp + full transitive dependency tree
      "./node_modules/sharp/**/*",
      "./node_modules/@img/**/*",
      "./node_modules/detect-libc/**/*",
      "./node_modules/semver/**/*",
      "./node_modules/color/**/*",
      "./node_modules/color-convert/**/*",
      "./node_modules/color-name/**/*",
      "./node_modules/color-string/**/*",
      "./node_modules/simple-swizzle/**/*",
      "./node_modules/is-arrayish/**/*",
      // node-vibrant + full transitive dependency tree
      "./node_modules/node-vibrant/**/*",
      "./node_modules/lodash/**/*",
      "./node_modules/@babel/runtime/**/*",
      "./node_modules/regenerator-runtime/**/*",
      "./node_modules/@jimp/**/*",
      "./node_modules/any-base/**/*",
      "./node_modules/buffer/**/*",
      "./node_modules/base64-js/**/*",
      "./node_modules/ieee754/**/*",
      "./node_modules/exif-parser/**/*",
      "./node_modules/file-type/**/*",
      "./node_modules/readable-web-to-node-stream/**/*",
      "./node_modules/strtok3/**/*",
      "./node_modules/token-types/**/*",
      "./node_modules/load-bmfont/**/*",
      "./node_modules/buffer-equal/**/*",
      "./node_modules/mime/**/*",
      "./node_modules/parse-bmfont-ascii/**/*",
      "./node_modules/parse-bmfont-binary/**/*",
      "./node_modules/parse-bmfont-xml/**/*",
      "./node_modules/phin/**/*",
      "./node_modules/xhr/**/*",
      "./node_modules/xtend/**/*",
      "./node_modules/mkdirp/**/*",
      "./node_modules/minimist/**/*",
      "./node_modules/pixelmatch/**/*",
      "./node_modules/pngjs/**/*",
      "./node_modules/tinycolor2/**/*",
      "./node_modules/bmp-js/**/*",
      "./node_modules/gifwrap/**/*",
      "./node_modules/image-q/**/*",
      "./node_modules/omggif/**/*",
      "./node_modules/jpeg-js/**/*",
      "./node_modules/utif/**/*",
      "./node_modules/pako/**/*",
      "./node_modules/timm/**/*",
      "./node_modules/url/**/*",
      "./node_modules/punycode/**/*",
      "./node_modules/qs/**/*",
      "./node_modules/side-channel/**/*",
      "./node_modules/side-channel-list/**/*",
      "./node_modules/side-channel-map/**/*",
      "./node_modules/side-channel-weakmap/**/*",
      "./node_modules/es-errors/**/*",
      "./node_modules/object-inspect/**/*",
      // other pipeline deps
      "./node_modules/form-data/**/*",
    ],
  },
};

export default nextConfig;
